//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public System.DateTime NgayDangBai { get; set; }
        public string TieuDe { get; set; }
        public int NguoiDang { get; set; }
        public string NoiDung { get; set; }
        public int LoaiBaiViet { get; set; }
        public string picture { get; set; }
    
        public virtual LoaiBaiViet LoaiBaiViet1 { get; set; }
        public virtual NhanVienKhoa NhanVienKhoa { get; set; }
    }
}
