//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatThanhTich
    {
        public int ID { get; set; }
        public int NguoiDatThanhTich { get; set; }
        public int ThanhTich { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual ThanhTich ThanhTich1 { get; set; }
        public virtual NhanVienKhoa NhanVienKhoa { get; set; }
    }
}
