//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanHoiKhoa
    {
        public int ID { get; set; }
        public Nullable<int> MSSV { get; set; }
        public string ChucVu { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
