//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class LoginAdmin
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập dữ liệu")]
        public string username { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập dữ liệu")]
        public string password { get; set; }
    }
}
