//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int ID { get; set; }
        public string MSSV { get; set; }
        public string HoTen { get; set; }
        public string NienKhoa { get; set; }
        public Nullable<int> SoDienThoai { get; set; }
        public string mail { get; set; }
    }
}
