//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDung
    {
        public int ID { get; set; }
        public string ViTri { get; set; }
        public int SoLuong { get; set; }
        public string YeuCau { get; set; }
        public string ChiTiet { get; set; }
    }
}
